name: claims-management-joe

dependencies:
- python==3.7
- spyder==3.3.6
- pip:
  - tensorboard==2.1.0
  - pandas==0.25.1
  - torch==1.7.1 -f https://download.pytorch.org/whl/torch_stable.html
  - scikit_optimize==0.7.1
  - tqdm==4.36.1
  - scikit-learn==0.21.3
  - https://github.com/ildoonet/pytorch-gradual-warmup-lr/zipball/master
  